// Completed in 2.11367 seconds.
#pragma once
#include <cstdint>

// Roblox Version: version-d34359a5577645e2
namespace Offsets {
    enum External : uintptr_t {

         Adornee = 0xd0,                                       
         AnchoredMask = 0x2,                                   
         AnimationId = 0xd0,                                   
         AutoJump = 0x1d8,                                     
         AutoRotate = 0x1d9,                                   
         BrickColor = 0x1bc,                                   
         Camera = 0x448,                                       
         CameraFocus = 0x128,                                  
         CameraPosition = 0x11c,                               
         CameraRotation = 0xf8,                                
         CameraSubject = 0xe8,                                 
         CanCollideMask = 0x8,                                 
         CanTouchMask = 0x10,                                  
         CelestialBodiesShown = 0x228,                         
         Children = 0x60,                                      
         ChildrenSize = 0x8,                                   
         ClassDescriptor = 0x18,                               
         ClassDescriptorToClassName = 0x8,                     
         ColorShiftBottom = 0x20c,                             
         ColorShiftTop = 0x218,                                
         CreatorId = 0x188,                                    
         DataModelDeleterPointer = 0x720a130,                  
         DataModelToRenderView1 = 0x1d0,                       
         DataModelToRenderView2  = 0x8,                        
         DataModelToRenderView3  = 0x28,                       
         DecalTexture = 0x198,                                 
         Dimensions = 0x720,                                   
         DisplayName = 0x110,                                  
         FOV = 0x160,                                          
         FakeDataModelPointer = 0x720a138,                     
         FakeDataModelToRealDataModel = 0x1c0,                 
         FogEnd = 0x134,                                       
         FogStart = 0x138,                                     
         FramePositionOffsetX = 0x4d4,                         
         FramePositionOffsetY = 0x4dc,                         
         FramePositionX = 0x4d0,                               
         FramePositionY = 0x4d8,                               
         FrameRotation = 0x188,                                
         GameId = 0x190,                                       
         GameLoaded = 0x680,                                   
         Gender = 0xe30,                                       
         GetSetImplementation = 0xa0,                          
         GlobalShadows = 0x130,                                
         GlobalState = 0x138,                                  
         Health = 0x194,                                       
         HumanoidState = 0x858,                                
         HumanoidStateId = 0x20,                               
         InputObject1 = 0x100,                                 
         InputObject2 = 0x110,                                 
         IsCoreScript = 0x188,                                 
         JobId = 0x138,                                        
         JobsPointer = 0x7434348,                              
         Jump = 0x1dd,                                         
         JumpPower = 0x1b0,                                    
         LocalPlayer = 0x120,                                  
         MaxHealth = 0x1b4,                                    
         MaxSlopeAngle = 0x1b8,                                
         MeshId = 0x308,                                       
         ModelInstance = 0x340,                                
         MousePosition = 0xec,                                 
         MoveDirection = 0x158,                                
         Name = 0x80,                                          
         NameDisplayDistance = 0x1bc,                          
         NameSize  = 0x10,                                     
         Overlap = 0x288,                                      
         Parent = 0x50,                                        
         PartPosition = 0x11c,                                 
         PartRotation = 0xf8,                                  
         PartVelocity = 0x128,                                 
         Ping = 0xd0,                                          
         PlaceId = 0x198,                                      
         PlaceVersion = 0x53c,                                 
         PlatformName = 0xe70,                                 
         PlatformStand = 0x1df,                                
         PrimaryPart = 0x260,                                  
         Primitive = 0x170,                                    
         PrimitiveCount = 0x4c0,                               
         PrimitiveValidateValue = 0x6,                         
         PrimitivesPointer1 = 0x3d0,                           
         PrimitivesPointer2 = 0x210,                           
         PropertyDescriptor = 0xd48,                           
         ReadOnlyGravity = 0x990,                              
         RenderViewToVisualEngine = 0x10,                      
         ReplicatorAnimationTrackLimitPerAnimator = 0x6090ef8, 
         RequireBypass = 0x870,                                
         RigType = 0x1c8,                                      
         Rotation = 0x100,                                     
         RotationVelocity = 0x134,                             
         ScriptContext = 0x3d0,                                
         SensitivityPointer = 0x738bdb0,                       
         ServerIp = 0x668,                                     
         ShapeType = 0x20d,                                    
         Sit = 0x1e1,                                          
         SkyboxBk = 0xd8,                                      
         SkyboxDn = 0x100,                                     
         SkyboxFt = 0x128,                                     
         SkyboxLf = 0x150,                                     
         SkyboxRt = 0x178,                                     
         SkyboxUp = 0x1a0,                                     
         StarCount = 0x220,                                    
         TaskSchedulerPointer = 0x7434168,                     
         Team = 0x250,                                         
         TeamColor = 0xd0,                                     
         TextLabelText = 0xde8,                                
         Texture = 0x198,                                      
         UserId = 0x288,                                       
         Value = 0xd0,                                         
         ViewMatrix = 0x4b0,                                   
         VisualEnginePointer = 0x6f6fc30,                      
         VisualEngineToDataModel1 = 0x700,                     
         VisualEngineToDataModel2 = 0x1c0,                     
         Walkspeed = 0x1d4,                                    
         WalkspeedCheck = 0x27e,                               
         Workspace = 0x178,                                    
         WorldStepMax = 0x6094818,                             
         WorldStepsOffsetAdjustRate = 0x609481c,               

        constexpr size_t TotalOffsets = 116;

    };
}

