// Completed in 8.90602 seconds.
#pragma once
#include <cstdint>

// Roblox Version: version-7a4a5d7d1fb3449f
namespace Offsets {
    enum External : uintptr_t {

         Adornee = 0xd0,                                       
         Ambient = 0xd8,                                       
         Anchored = 0x26d,                                     
         AnchoredMask = 0x2,                                   
         AnimationId = 0xd0,                                   
         AutoJump = 0x1d8,                                     
         AutoRotate = 0x1d9,                                   
         BrickColor = 0x1bc,                                   
         Camera = 0x448,                                       
         CameraFocus = 0x128,                                  
         CameraMaxZoomDistance = 0x2d0,                        
         CameraMinZoomDistance = 0x2d4,                        
         CameraPosition = 0x11c,                               
         CameraRotation = 0xf8,                                
         CameraSubject = 0xe8,                                 
         CanCollide = 0x26d,                                   
         CanCollideMask = 0x8,                                 
         CanTouch = 0x26d,                                     
         CanTouchMask = 0x10,                                  
         CelestialBodiesShown = 0x228,                         
         Children = 0x60,                                      
         ChildrenSize = 0x8,                                   
         ClassDescriptor = 0x18,                               
         ClassDescriptorToClassName = 0x8,                     
         ColorShiftBottom = 0xe4,                              
         ColorShiftTop = 0xf0,                                 
         CreatorId = 0x188,                                    
         DataModelDeleterPointer = 0x7268a80,                  
         DataModelToRenderView2  = 0x8,                        
         DataModelToRenderView3  = 0x28,                       
         DecalTexture = 0x198,                                 
         DisplayName = 0x110,                                  
         EnableDefaultVoice = 0x210,                           
         FOV = 0x160,                                          
         FakeDataModelPointer = 0x7268a88,                     
         FakeDataModelToRealDataModel = 0x1c0,                 
         FogColor = 0xfc,                                      
         FogEnd = 0x134,                                       
         FogStart = 0x138,                                     
         FramePositionOffsetX = 0x4dc,                         
         FramePositionOffsetY = 0x4e4,                         
         FramePositionX = 0x4d8,                               
         FramePositionY = 0x4e0,                               
         FrameRotation = 0x188,                                
         GameId = 0x190,                                       
         GameLoaded = 0x640,                                   
         Gender = 0xe30,                                       
         GetSetImplementation = 0xa0,                          
         GlobalShadows = 0x130,                                
         GlobalState = 0x138,                                  
         Health = 0x194,                                       
         HumanoidState = 0x858,                                
         HumanoidStateId = 0x20,                               
         InputObject1 = 0x100,                                 
         InputObject2 = 0x110,                                 
         IsCoreScript = 0x188,                                 
         JobId = 0x138,                                        
         JobsPointer = 0x75be390,                              
         Jump = 0x1dd,                                         
         JumpPower = 0x1b0,                                    
         LocalPlayer = 0x120,                                  
         MaxHealth = 0x1b4,                                    
         MaxSlopeAngle = 0x1b8,                                
         MeshId = 0x308,                                       
         ModelInstance = 0x340,                                
         MoonTextureId = 0xd8,                                 
         MousePosition = 0xec,                                 
         MoveDirection = 0x158,                                
         Name = 0x80,                                          
         NameDisplayDistance = 0x1bc,                          
         NameSize  = 0x10,                                     
         OutDoorAmbient = 0x108,                               
         Overlap = 0x288,                                      
         Parent = 0x50,                                        
         PartPosition = 0x11c,                                 
         PartRotation = 0xf8,                                  
         PartSize = 0x1cc,                                     
         PartVelocity = 0x128,                                 
         Ping = 0xd0,                                          
         PlaceId = 0x198,                                      
         PlaceVersion = 0x4fc,                                 
         PlatformName = 0xe70,                                 
         PlatformStand = 0x1df,                                
         PrimaryPart = 0x260,                                  
         Primitive = 0x170,                                    
         PrimitiveCount = 0x36b,                               
         PropertyDescriptor = 0x16c8,                          
         ReadOnlyGravity = 0x990,                              
         RenderViewToVisualEngine = 0x10,                      
         ReplicatorAnimationTrackLimitPerAnimator = 0x60eaf18, 
         RequireBypass = 0x870,                                
         RigType = 0x1c8,                                      
         Rotation = 0x100,                                     
         RotationVelocity = 0x134,                             
         ScriptContext = 0x3d0,                                
         ServerIp = 0x628,                                     
         ShadowColor = 0x114,                                  
         ShapeType = 0x28a,                                    
         Sit = 0x1e1,                                          
         SkyboxBk = 0xd8,                                      
         SkyboxDn = 0x100,                                     
         SkyboxFt = 0x128,                                     
         SkyboxLf = 0x150,                                     
         SkyboxRt = 0x178,                                     
         SkyboxUp = 0x1a0,                                     
         StarCount = 0x220,                                    
         SunTextureId = 0x1f0,                                 
         TaskSchedulerPointer = 0x75be1b8,                     
         TaskSchedulerTargetFps = 0x6a23e04,                   
         Team = 0x250,                                         
         TeamColor = 0xd0,                                     
         TextLabelText = 0xdf0,                                
         Texture = 0x198,                                      
         UserId = 0x288,                                       
         Value = 0xd0,                                         
         ViewMatrix = 0xd90,                                   
         VisualEnginePointer = 0x6fcc830,                      
         VisualEngineToDataModel1 = 0x700,                     
         VisualEngineToDataModel2 = 0x1c0,                     
         Walkspeed = 0x1d4,                                    
         WalkspeedCheck = 0x3a0,                               
         Workspace = 0x178,                                    
         WorldStepMax = 0x60ee844,                             
         WorldStepsOffsetAdjustRate = 0x60ee848,               

         Total = 124 offsets;

    };
}

